#!/usr/bin/env bash
USERNAME=volgactf
IMAGE=volgactf-qualifier-frontend

version=`cat VERSION`
echo "version: $version"

docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$version
docker push $USERNAME/$IMAGE:latest
docker push $USERNAME/$IMAGE:$version
